"""Add nullable category to WeddingPackage model

Revision ID: 0724c308880b
Revises: 57deae7b91f0
Create Date: 2025-07-09 13:11:27.479931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0724c308880b'
down_revision = '57deae7b91f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wedding_package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wedding_package', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
