"""Add HeroImage table

Revision ID: 160759bfc2ce
Revises: a22b53084618
Create Date: 2025-07-12 18:00:42.065900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160759bfc2ce'
down_revision = 'a22b53084618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=150), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_image', schema=None) as batch_op:
        batch_op.drop_column('is_hero_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hero_image', sa.BOOLEAN(), nullable=False))

    op.drop_table('hero_image')
    # ### end Alembic commands ###
