"""Add cancellation and reschedule fields to Order model

Revision ID: 1b88a5dfa8af
Revises: 160759bfc2ce
Create Date: 2025-07-13 04:13:14.383610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b88a5dfa8af'
down_revision = '160759bfc2ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reschedule_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requested_event_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('requested_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('requested_end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('requested_end_time')
        batch_op.drop_column('requested_start_time')
        batch_op.drop_column('requested_event_date')
        batch_op.drop_column('reschedule_reason')
        batch_op.drop_column('cancellation_reason')

    # ### end Alembic commands ###
