"""Add likes to PostImage

Revision ID: 57deae7b91f0
Revises:
Create Date: 2025-07-08 21:02:29.325319

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57deae7b91f0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_image", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("likes", sa.Integer(), nullable=False, server_default="0")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_image", schema=None) as batch_op:
        batch_op.drop_column("likes")

    # ### end Alembic commands ###
