"""Add dp_payment_proof to Order

Revision ID: 6ec4dd31b189
Revises: b8ccd89c6a5b
Create Date: 2025-07-06 17:27:40.647283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec4dd31b189'
down_revision = 'b8ccd89c6a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dp_payment_proof', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('dp_payment_proof')

    # ### end Alembic commands ###
