"""Add payment_type to Order model

Revision ID: 8db7b12f7661
Revises: c6f0b1c9e6e7
Create Date: 2025-07-23 05:25:37.358102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db7b12f7661'
down_revision = 'c6f0b1c9e6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        # 1. Tambahkan kolom sebagai nullable=True terlebih dahulu
        batch_op.add_column(sa.Column('payment_type', sa.String(length=50), nullable=True))

    # 2. Perbarui semua baris yang sudah ada dengan nilai default 'dp'
    op.execute("UPDATE \"order\" SET payment_type = 'dp' WHERE payment_type IS NULL")

    with op.batch_alter_table('order', schema=None) as batch_op:
        # 3. Ubah kolom menjadi nullable=False
        batch_op.alter_column('payment_type',
                              existing_type=sa.String(length=50),
                              nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###