"""Add event start and end times to Order model

Revision ID: a0ce1d393fec
Revises:
Create Date: 2025-07-06 02:02:08.965034

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0ce1d393fec"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("event_start_time", sa.DateTime(), nullable=False)
        )
        batch_op.add_column(sa.Column("event_end_time", sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.drop_column("event_end_time")
        batch_op.drop_column("event_start_time")

    # ### end Alembic commands ###
