"""Add homepage content management and hero image selection

Revision ID: a22b53084618
Revises: 6308bce484d2
Create Date: 2025-07-12 17:23:14.623618

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a22b53084618"
down_revision = "6308bce484d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("post_image", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_hero_image", sa.Boolean(), nullable=True))

    op.execute("UPDATE post_image SET is_hero_image = FALSE")

    with op.batch_alter_table("post_image", schema=None) as batch_op:
        batch_op.alter_column(
            "is_hero_image", existing_type=sa.Boolean(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_image", schema=None) as batch_op:
        batch_op.drop_column("is_hero_image")

    op.drop_table("homepage_content")
    # ### end Alembic commands ###
