"""Add unique constraint to BankAccount.account_number and validate digits

Revision ID: b372384a0f0d
Revises: cae66c0798d7
Create Date: 2025-07-07 17:15:47.676384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b372384a0f0d'
down_revision = 'cae66c0798d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_bank_account_number', ['account_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bank_account_number', type_='unique')

    # ### end Alembic commands ###
