"""Add wedding_package_id to Order model

Revision ID: b8ccd89c6a5b
Revises: 48f4aa026721
Create Date: 2025-07-06 02:39:10.902834

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b8ccd89c6a5b"
down_revision = "48f4aa026721"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("wedding_package_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_order_wedding_package_id",
            "wedding_package",
            ["wedding_package_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("wedding_package_id")

    # ### end Alembic commands ###
