"""Set is_client_hidden to NOT NULL and default False

Revision ID: c6f0b1c9e6e7
Revises: 8deeb9f1f85d
Create Date: 2025-07-19 19:01:53.381099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f0b1c9e6e7'
down_revision = '8deeb9f1f85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE 'order' SET is_client_hidden = 0 WHERE is_client_hidden IS NULL")
    with op.batch_alter_table('order', schema=None) as batch_op:

        batch_op.alter_column('is_client_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('is_client_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
