"""Add total_price, dp_paid to Order and update status workflow

Revision ID: d0a1e5ddda5a
Revises: a0ce1d393fec
Create Date: 2025-07-06 02:19:01.787603

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d0a1e5ddda5a"
down_revision = "a0ce1d393fec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "total_price", sa.Float(), nullable=False, server_default=sa.text("0.0")
            )
        )
        batch_op.add_column(
            sa.Column(
                "dp_paid", sa.Float(), nullable=False, server_default=sa.text("0.0")
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.drop_column("dp_paid")
        batch_op.drop_column("total_price")

    # ### end Alembic commands ###
