"""Add 
     cancellation_requested to Order model

Revision ID: d70933dfc903
Revises: 1b88a5dfa8af
Create Date: 2025-07-13 04:59:58.664707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70933dfc903'
down_revision = '1b88a5dfa8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_requested', sa.Boolean(), nullable=True))

    op.execute('UPDATE "order" SET cancellation_requested = FALSE WHERE cancellation_requested IS NULL')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('cancellation_requested', existing_type=sa.Boolean(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('cancellation_requested')

    # ### end Alembic commands ###
