"""Make event_start_time and event_end_time nullable in Order model

Revision ID: f9d6247d5ad4
Revises: 0724c308880b
Create Date: 2025-07-09 14:02:13.531102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d6247d5ad4'
down_revision = '0724c308880b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('event_start_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('event_end_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('event_end_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('event_start_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
